generate-datasource:
  - id: kbssoptsett
    table-list: TRDACCT_ROUTINIZATION
#  url = jdbc:mysql://localhost:3306/test?useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#  username = root
#  password = 991226Ab#
#  # mysql数据库链接数要设置大一点，太小了在保存数据时会不够用
#  maxActive=16