generate: cur
datasourceGroupList:
  - dataSourceId: mysql
    columnConfig:
      - colName: id
        strategy: default
    tableConfig:
      - a:50000
  - dataSourceId: cur
    columnConfig:
      - colName: STK_CODE,REC_SN,FEE_TEMPLATE_ID,INT_ORG,FEE_CFG_SN,FEE_CFG_ID,FEE_TEMPLATE_CFG_SN,ORIGIN_TMPL_SN
        strategy: default
      - colName: ABN_REASON
        strategy: dict-value
      - colName: OPT_NUM
        strategy: auto-inc
        baseValue: 600000
      - colName: CUACCT_CODE
        strategy: auto-inc
        baseValue: 2200000000
      - colName: TRDACCT
        strategy: auto-inc
        baseValue: 56200000
      - colName: COMB_NUM
        strategy: auto-inc
        baseValue: 1100000
      - colName: LEG1_TYPE,LEG2_TYPE,LEG3_TYPE,LEG4_TYPE
        strategy: dict-value
        dictColName: OPT_TYPE
      - colName: LEG1_SIDE,LEG2_SIDE,LEG3_SIDE,LEG4_SIDE
        strategy: dict-value
        dictColName: OPT_SIDE
      - colName: LEG1_NUM,LEG2_NUM,LEG3_NUM,LEG4_NUM
        strategy: rand-table-ele
        querySql: "select OPT_NUM  from OPT_INFO"
        queryCol: OPT_NUM
      - colName: CURRENCY
        strategy: rand-ele
        randomEle: ["0","1","2"]
      - colName: CONFIRM_FLAG
        strategy: rand-ele
        randomEle: ["0","1"]
      - colName: CUST_CODE
        strategy: auto-inc
        baseValue: 1200000000
      - colName: CHANNELES
        strategy: dict-value
        dictColName: CHANNEL
      - colName: CUACCT_LVLS
        strategy: dict-value
        dictColName: CUACCT_LVL
      - colName: CUACCT_CLSES
        strategy: dict-value
        dictColName: CUACCT_CLS
      - colName: CUACCT_GRPS
        strategy: dict-value
        dictColName: CUACCT_GRP
      - colName: FEE_TEMPLATE_NAME
        strategy: auto-inc
        baseValue: 0
        prefix: 模板名称
      - colName: FEE_TEMPLATE_DESC
        strategy: auto-inc
        baseValue: 0
        prefix: 模板描述
      - colName: FEE_ID
        strategy: rand-table-ele
        querySql: "select FEE_ID from FEE_DEFINE"
        queryCol: FEE_ID
#      - colName: FEE_CAL_AMT
#        strategy: auto-inc
#        querySql: "select FEE_ID from FEE_DEFINE"
#        queryCol: FEE_ID
      - colName: STK_CLSES
        strategy: dict-value
        dictColName: STK_CLS
      - colName: BIZ_CODES
        strategy: dict-value
        dictColName: BIZ_CODE
      - colName: COMMISION_MODE
        strategy: rand-ele
        randomEle: ["0","1","2"]
      - colName: TMPL_ORIGIN
        strategy: rand-ele
        randomEle: ["0","1","2","3"]
      - colName: CHARGE_TYPE
        strategy: rand-ele
        randomEle: ["0","1"]
    tableConfig:
      # 佣金模板配置
      - COMM_TEMPLATE:1000
      # 机构配置
      - BRANCH_ORG_CFG:1000
      # 资金账号配置
      - CUACCT_FEE_CFG:1000
      # 费用模板声明
      - FEE_TEMPLATE_DEFINE:1000
      # 按证券类别的费用配置
      - STKCLS_STDFEE_RATE:1000
      # 按证券代码的费用配置
      - STKCODE_STDFEE_RATE:1000
      # 分段配置
      - SUB_CAL_CFG:1000
      - CUST_SETT:200000:0
      - OPT_INFO:100000:0
      - STKCLS_STDFEE_RATE:100000:0
      - OPT_CLOSE_PRICE:100000:0
      - OPT_ADJUST_INFO:100000:0
      - OPT_ASSET:100000:0
      - Q_CUACCT_FUND:100000:0
      - OPT_CUACCT_FUND:100000:0
      - OPT_COMB_ASSET:100000:0
    dictConfig:
      dictTableName: UPM_DICT_ITEMS
      dictCodeColName: DICT_CODE
      dictItemColName: DICT_ITEM
    loadDictCache: true
    colDefaultValue:
      MAX_FEE: 500
      MIN_FEE: 0
      SETT_DATE: 20230404
      TRD_DATE: 20230404
      MARKET: 1
      BOARD: 15
      SUB_CUACCT_CODE: 0
      FEE_CAL_AMT: 100
      FEE_MAX: 100
      FEE_MIN: 0
      FEE_RATE: 1
    ignoreCol: PARTITION_FIELD
  - dataSourceId: his
    columnConfig:
      - colName: STK_CODE
        strategy: default
      - colName: ABN_REASON
        strategy: dict-value
      - colName: OPT_NUM
        strategy: auto-inc
        baseValue: 600000
      - colName: FEE_CFG_SN
        strategy: default
      - colName: CUACCT_CODE
        strategy: auto-inc
        baseValue: 2200000000
      - colName: TRDACCT
        strategy: auto-inc
        baseValue: 56200000
      - colName: COMB_NUM
        strategy: auto-inc
        baseValue: 1100000
      - colName: LEG1_TYPE,LEG2_TYPE,LEG3_TYPE,LEG4_TYPE
        strategy: dict-value
        dictColName: OPT_TYPE
      - colName: LEG1_SIDE,LEG2_SIDE,LEG3_SIDE,LEG4_SIDE
        strategy: dict-value
        dictColName: OPT_SIDE
      - colName: LEG1_NUM,LEG2_NUM,LEG3_NUM,LEG4_NUM
        strategy: rand-table-ele
        querySql: "select OPT_NUM  from OPT_INFO"
        queryCol: OPT_NUM
      - colName: CURRENCY
        strategy: rand-ele
        randomEle: ["0","1","2"]
      - colName: CONFIRM_FLAG
        strategy: rand-ele
        randomEle: ["0","1"]
      - colName: CUST_CODE
        strategy: auto-inc
        baseValue: 1200000000
    tableConfig:
      - CUST_SETT:200000
      - OPT_INFO:100000:0
      - STKCLS_STDFEE_RATE:100000:0
      - OPT_CLOSE_PRICE:100000:0
      - OPT_ADJUST_INFO:100000:0
      - OPT_ASSET:100000:0
      - Q_CUACCT_FUND:100000:0
      - OPT_CUACCT_FUND:100000:0
      - OPT_COMB_ASSET:100000:0
    colDefaultValue:
      SETT_DATE: 20230404
      TRD_DATE: 20230404
      MARKET: 1
      BOARD: 15
      SUB_CUACCT_CODE: 0